name: lpl_auction_app
description: "LPL Auction System Mobile App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  http: ^1.1.0
  socket_io_client: ^3.1.3
  shared_preferences: ^2.2.0
  google_fonts: ^8.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo_app.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo_app.jpg"
  web:
    generate: true
    image_path: "assets/logo_app.jpg"
    background_color: "#hex"
    theme_color: "#hex"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/teams/

